In [21]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\spaceastonomy\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


#사이킷 런을 했는데, 붓꽃 2덩이를 5개로 나누고, 
의사결정나무(DecisionTress) 와, 로지스틱(Losistic) 으로 테스팅을 해봤다. 


수단으로 sklearn.tree.DecisionTreeClassifier
수단으로 sklearn.metrics.accuracy_score
수단으로 sklearn.model_selection.KFold

#### 

### 1. sklearn.model_selection.KFold
* class sklearn.model_selection.KFold(n_splits=5, *, shuffle=False, random_state=None)

In [3]:
from sklearn.tree import DecisionTreeClassifier #알고리즘 선택
from sklearn.metrics import accuracy_score #정확도를 측정하는 함수
from sklearn.model_selection import KFold #k폴드 교차 검증 선택 
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


In [23]:
iris.data #인덱스를 의미한다. 

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
n_iter = 0 
kfold.split(features)

<generator object _BaseKFold.split at 0x00000225EFF45F50>

In [5]:
a = [i for i in kfold.split(features)]
a

[(array([ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
          43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
          56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,
          69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,
          82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
          95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
         108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
         121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
         134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
         147, 148, 149]),
  array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])),
 (array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
          13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
          26,  27, 

In [6]:
for i in kfold.split(features):
    print(i)

(array([ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
        43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
        56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,
        69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,
        82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
        95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
       108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
       121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
       134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
       147, 148, 149]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]))
(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  60,  61,  62,  63,

In [8]:
for t, x in kfold.split(features):
    print(t)

[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
[  0   1   2   3   4   5

In [26]:
for train_index, test_index in kfold.split(features):
    print(train_index)
    
#print(features[30])

[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
[  0   1   2   3   4   5

In [74]:
for i, j in kfold.split(features): #range(5)
    X_train, X_test = features[test_index], features[test_index]
    y_train, y_test = label[test_index], label[test_index]
    
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    
    accuracy = np.round(accuracy_score(y_test,pred), 4)
    print(X_train.shape)

(24, 4)
(24, 4)
(24, 4)
(24, 4)
(24, 4)


In [28]:
nn_iter = 0

for i, j in kfold.split(features):
    X_train, X_test = features[i], features[j]
    y_train, y_test = label[i], label[j]
    
    dt_clf.fit(X_train, y_train) #120 
    pred = dt_clf.predict(X_test) #30
    nn_iter += 1
    
    accuracy = np.round(accuracy_score(y_test,pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    # print('\n#{0} 교차 검증 정확도 : {1}, 학습데이터 )
    
    print(f'#{nn_iter} 교차 검증 정확도 {accuracy} . 학습데이터 크기 {train_size}, 검증 크기{test_size}')
    print(f'#{nn_iter}, 검증 세트 인덱스 {test_index}')
    cv_accuracy.append(accuracy)
    
print(f'\n ## 평균 검증 정확도 {np.mean(cv_accuracy)}')

#1 교차 검증 정확도 1.0 . 학습데이터 크기 120, 검증 크기30
#1, 검증 세트 인덱스 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
#2 교차 검증 정확도 0.9667 . 학습데이터 크기 120, 검증 크기30
#2, 검증 세트 인덱스 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
#3 교차 검증 정확도 0.8667 . 학습데이터 크기 120, 검증 크기30
#3, 검증 세트 인덱스 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
#4 교차 검증 정확도 0.9333 . 학습데이터 크기 120, 검증 크기30
#4, 검증 세트 인덱스 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
#5 교차 검증 정확도 0.7333 . 학습데이터 크기 120, 검증 크기30
#5, 검증 세트 인덱스 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

 ## 평균 검증 정확도 0.9


In [29]:
from sklearn.linear_model import LogisticRegression

cl_arr = ['DecisionTreeClassifier()', 'LogisticRegression(max_iter=3000)']
for i in cl_arr:
    dt_clf =  eval(i)
    for train_index, test_index in kfold.split(features):
        X_train, X_test = features[train_index], features[test_index]
        y_train, y_test = label[train_index], label[test_index]             
        
        dt_clf.fit(X_train, y_train)
        pred = dt_clf.predict(X_test)
        n_iter += 1
        
        accuracy = np.round(accuracy_score(y_test,pred), 4)
        train_size = X_train.shape[0]
        test_size = X_test.shape[0]
        # print('\n#{0} 교차 검증 정확도 : {1}, 학습데이터 )
        
        print(f'#{n_iter} 교차 검증 정확도 {accuracy} . 학습데이터 크기 {train_size}, 검증 크기{test_size}')
        print(f'#{n_iter}, 검증 세트 인덱스 {test_index}')
        cv_accuracy.append(accuracy)
    
    print(f'\n ## 평균 검증 정확도 {np.mean(cv_accuracy)}')

#6 교차 검증 정확도 1.0 . 학습데이터 크기 120, 검증 크기30
#6, 검증 세트 인덱스 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
#7 교차 검증 정확도 0.9667 . 학습데이터 크기 120, 검증 크기30
#7, 검증 세트 인덱스 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
#8 교차 검증 정확도 0.8333 . 학습데이터 크기 120, 검증 크기30
#8, 검증 세트 인덱스 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]
#9 교차 검증 정확도 0.9333 . 학습데이터 크기 120, 검증 크기30
#9, 검증 세트 인덱스 [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
#10 교차 검증 정확도 0.7333 . 학습데이터 크기 120, 검증 크기30
#10, 검증 세트 인덱스 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

 ## 평균 검증 정확도 0.89666
#11 교차 검증 정확도 1.0 . 학습데이터 크기 120, 검증 크기30
#11, 검증 세트 인덱스 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
#12 교차 검증 정확도

#### 2. sklearn.model_selection.StratifiedKFold
* class sklearn.model_selection.StratifiedKFold(n_splits=5, *, shuffle=False, random_state=None)

In [30]:
import pandas as pd

iris = load_iris()

iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [31]:
from sklearn.model_selection import StratifiedKFold

iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

skf = StratifiedKFold(n_splits = 3)
n_iter = 0



for train_index, test_index in kfold.split(train_index):
           n_iter +=1
           label_train = iris_df['label'].iloc[train_index]
           label_test = iris_df['label'].iloc[test_index]
           print(f'#{n_iter} 교차 검증 {0}')
           print('학습 레이블 데이터 분포:\n', label_train.value_counts())
           print('검증 레이블 데이터 분포:\n', label_test.value_counts())

#1 교차 검증 0
학습 레이블 데이터 분포:
 1    50
0    26
2    20
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    24
Name: label, dtype: int64
#2 교차 검증 0
학습 레이블 데이터 분포:
 1    50
0    26
2    20
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    24
Name: label, dtype: int64
#3 교차 검증 0
학습 레이블 데이터 분포:
 0    48
1    28
2    20
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    22
0     2
Name: label, dtype: int64
#4 교차 검증 0
학습 레이블 데이터 분포:
 0    50
1    26
2    20
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    24
Name: label, dtype: int64
#5 교차 검증 0
학습 레이블 데이터 분포:
 0    50
1    46
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    20
1     4
Name: label, dtype: int64


#### 3. sklearn.model_selection.cross_val_score
* sklearn.model_selection.cross_val_score(estimator, X, y=None, *, groups=None, scoring=None, cv=None, n_jobs=None, verbose=0, fit_params=None, pre_dispatch='2*n_jobs', error_score=nan)

cross_val_score() : 교차 검증을 보다 간단히게
앞서 수행한 Kfold로 데이터를 학습하고, 예측하는 코드를 보면 아래와 같은 프로세스로 검증이 진행되었음

(1) 폴드 세트 설정 (2) for 루프 반복으로 학습 및 테스트 데이터의 인덱스를 추출 (3) 반복적으로 학습과 예측을 수행하고 예측수행을 반환

cross_val_score() 는 이 과정을 한꺼번에 수행해주는 API
cross_val_score() API의 선언형태
--> cross_val_score(estimator, X, y=None, scoring=None, cv=None, n_jobs=1, verbose =0, fit_params=None, pre_dispatch = '2*n_jobs')

estimator : 예측모델
X : 피처 데이터 세트
y : 레이블 데이터 세트,
scoring : 예측성능평가 지표
cv : 교차검증 폴드 수 (estimator로 classifier가 입력되면 Stratified Kfold 방식으로 학습/테스트 데이터 세트 분할)
수행 후 scoring 파라미터 값으로 지정된 성능 지표를 배열 형태로 반환

교차검증을 보다 간단하게 하기위한 방법
1. cross_val_score()를 사용한다.

앞서 수행한Kfold로 데이터를 학습하고, 예측하는 코드를 보면 아래와 같은 프로세스로 검증이 진행되었다.

(1) 폴드셋 설정, (2) for 루프 반복으로 학습 및 테스트 데이터의 인덱스를 추출
(3) 반복적으로 학습과 예측을 수행하고 예측 수행을 반환

2. cross_val_score()는 과정을 한꺼번에 수행해 주는 api
3. 수단으로 sklearn.model_selection을 사용해서 그, 안에 

In [32]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

# 성능지표는 정확도(accuracy), 교차검증 세트는 3개
scores = cross_val_score(dt_clf, data, label, cv =3 , scoring = 'accuracy')
print('교차 검증별 정확도: ', np.round(scores, 4))
print('평균 검증 정확도: ', np.round(np.mean(scores),4))

교차 검증별 정확도:  [0.98 0.94 0.98]
평균 검증 정확도:  0.9667


GridSearchCV - 교차검증과 하이퍼파라미터 튜닝을 한번에
GridSearchCV를 이용하여 모델에 사용되는 하이퍼 파라미터를 순차적으로 입력하면서 최적의 파라미터를 도출


GridSearch의 주요 파라미터
estimator : 적용 알고리즘 모델로 classifier, regressor, pipeline 등이 사용
param_grid : ket+리스트 값을 가지는 딕셔너리가 주어짐. estimator의 튜닝을 위해 파라미터명과 사용될 여러 파라미터 값을 지어
scoring : 예측 성능을 평가할 평가 방법을 지정, 문자열로 사이킷런의 성능평가 지표를 입력하나 별도의 함수 지정도 가능
refit : 기본값은 True이며 True로 생성시 가장 최적의 하이퍼 파라미터를 찾은 뒤 입력된 estimator 객체를 해당 하이퍼 파리미터로 재학습시킴

교차검증과 하이퍼파라미터 튜닝을 한번에 하는 모듈: GridsearchCV

GridSearch를 이용하여 모델에 사용되는 하이퍼 파라미터를 순차적으로 입력하면서 최적의 파라미터를 도출

#### 4. sklearn.model_selection.GridSearchCV
* class sklearn.model_selection.GridSearchCV(estimator, param_grid, *, scoring=None, n_jobs=None, refit=True, cv=None, verbose=0, pre_dispatch='2*n_jobs', error_score=nan, return_train_score=False)

In [34]:
grid_parameters = {'max_depth': [1, 2, 3], 
                              'min_samples_split': [2, 3]}

In [35]:
pd.read_csv('Grid.csv', index_col= '순번')

FileNotFoundError: [Errno 2] No such file or directory: 'Grid.csv'

In [12]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
import pandas as pd

# 데이터를 로딩하고 학습데이터와 테스트 데이터 분리
iris = load_iris()

iris_date = iris.data
iris_target = iris.target
X_train, X_test, y_train, y_test = train_test_split(iris_date, iris_target, test_size = 0.2, random_state=121)

dtree = DecisionTreeClassifier()

## 파라미터를 딕셔너리 형태로 설정
parameters = {'max_depth' : [1, 2, 3], 'min_samples_split' : [2, 3]}


In [13]:
# param_grid의  하이퍼 파라미터를 3개의 train, test set fold로 나누어 테스트 수행 설정
## refit=True가 기본 설정으로 True이면 가장 좋은 파라미터 설정으로 재학습 시킴

grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

# 붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습, 평가
grid_dtree.fit(X_train, y_train)

# GridSearchCV 결과를 추출해 데이터 프레임으로 반환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [40]:
print('GridSearch 최적 파라미터: ', grid_dtree.best_params_)
print('GridSearch 최고 점수: ', grid_dtree.best_score_)

GridSearch 최적 파라미터:  {'max_depth': 3, 'min_samples_split': 2}
GridSearch 최고 점수:  0.975


In [41]:
# GridSearchCV의 refit으로 학습된 estimator 반환
estimator = grid_dtree.best_estimator_

# GridSearchCV의 best_estmator_ 는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
pred = estimator.predict(X_test)
print('테스트 데이터세트 정확도: {0: .4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터세트 정확도:  0.9667


In [2]:
import pymysql
import pandas as pd

_db = pymysql.connect(
    host="ls-a20f4420f7aa9967e25c1e0aecf4d8b641af5f13.cgtgapkuvqbt.ap-northeast-2.rds.amazonaws.com",
    db="ML",
    user = "dbmasteruser",
    password= "r,3Ipn|O7mL2vL4S)9Q~;7QVdHMV6R9j",
    port = 3306)

cursor = _db.cursor(pymysql.cursors.DictCursor) #딕셔너리 형태로 가져옴

search_sql = 'SELECT * From diabetes'

cursor.execute(search_sql)            
result = cursor.fetchall() 

dt_diabetes = pd.DataFrame(result)
dt_diabetes


################(오프라인 파일)##################
# # import pandas as pd
# dia = pd.read_csv('diabetes.csv')
# dia

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [70]:
dt_diabetes.iloc[0:4, 1:3]

Glucose  BloodPressure
0      148             72
1       85             66
2      183             64
3       89             66

# 사이킷 런으로 당뇨병 데이터 활용 
데이터를 불러와 split를 한다. 
impoert pandas하고, 수단으로 from sklearn.model_selection.train_test_split를 사용해서 데이터를 나눠 준다. 

x와 y의 학습데이터와, 테스트 데이터 변수를 각각 만들어 총 4개의 변수를 만들어 주고, 그 변수에 train_test_sprit함수를 사용해한다. 함수의 ()안에, 스플릿 해주기위한 변수를 넣어 준다.

넣어줄 변수는 1) outcome을 제외한 데이터프레임과 

수단으로 sklearn.tree.DecisionTreeClassifier을 불러와, 의사결정나무를 사용한다.
수단으로 sklearn.model_selection.cross_val_score를 불러와 교차검증을 편하게 쓰기위해 사용한다.
수단으로 sklearn.model_selection.GridSearchCV를 불러와 


In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score



dbt_data = dt_diabetes.iloc[:, 0:-1]

dbt_label = dt_diabetes.iloc[:, -1:] 


X_train, X_test, y_train, y_test = train_test_split(dbt_data, dbt_label,
                                                    test_size = 0.2, random_state = 121)

dtree = DecisionTreeClassifier()

parameters = {"max_depth" : [5, 6, 7], "min_samples_split":[2,3]}
grid_dtree = GridSearchCV(dtree, param_grid = parameters, cv = 3, refit = True)
grid_dtree.fit(X_train, y_train)


scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[["params", "mean_test_score", "rank_test_score",
            "split0_test_score", "split1_test_score", "split2_test_score"]]


print(f"GridSearchCV 최적 파라미터 : {grid_dtree.best_params_}")
print(f"GridSearchCV 최고 정확도 : {grid_dtree.best_score_ : .4f}")
estimator = grid_dtree.best_estimator_
pred = estimator.predict(X_test)
print(f"테스트 데이터 세트 정확도 {accuracy_score(y_test, pred):.4f}")

GridSearchCV 최적 파라미터 : {'max_depth': 5, 'min_samples_split': 2}
GridSearchCV 최고 정확도 :  0.7182
테스트 데이터 세트 정확도 0.7662


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
origin = pd.read_csv("diabetes.csv")
df_dbt = pd.DataFrame(origin)
dbt_data = df_dbt.iloc[:, 0:-1]
dbt_label = df_dbt.iloc[:, -1:]
X_train, X_test, y_train, y_test = train_test_split(dbt_data, dbt_label,
                                                    test_size = 0.2, random_state = 121)
dtree = DecisionTreeClassifier()
parameters = {"max_depth" : [5, 6, 7], "min_samples_split":[2,3]}
grid_dtree = GridSearchCV(dtree, param_grid = parameters, cv = 3, refit = True)
grid_dtree.fit(X_train, y_train)
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[["params", "mean_test_score", "rank_test_score",
            "split0_test_score", "split1_test_score", "split2_test_score"]]
print(f"GridSearchCV 최적 파라미터 : {grid_dtree.best_params_}")
print(f"GridSearchCV 최고 정확도 : {grid_dtree.best_score_ : .4f}")
estimator = grid_dtree.best_estimator_
pred = estimator.predict(X_test)
print(f"테스트 데이터 세트 정확도 {accuracy_score(y_test, pred):.4f}")

# 교차검증 방법 : kfold, statified

최적의 하이퍼 파라미터를 찾는 방법 --> 그리드 cv

지금 데이터를 갖고, 교차검증이라는 방법을 갖고 사용했다. 

