In [1]:
import numpy as np

### 중복없이 랜덤번호 출력 (다른 방법도 있음)
- https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html 참고

In [37]:
lotto = np.arange(45)+1
print(np.random.choice(lotto, 6 , replace=False , p=None)) # p는 default 값이 none이라서 안넣어주어도 됩니다.

[39 14 45  1 16 13]


### 정수 인덱싱 및 슬라이싱

In [29]:

data2 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

arr = np.array(data2)
arr1 = np.array([1, 2, 3]) 
arr2 = np.array([[1, 2, 3]]) 
print("원본\n",arr,"\n")
#인덱싱 
print("1번 인덱싱 ",arr[0][1],"\n")
print("2번 인덱싱 ",arr[0,1],"\n")

# 정수 배열 인덱싱 
print("3번 1차원 행만 인덱싱\n",arr1[[0,1]] ,"\n" ) # 1차원에 행 정보가 없기 때문에 열 index로 인덱싱
print("4번 1차원 행 2차원 인덱싱\n",arr2[[0]] ,"\n" ) # 2차원 [[ ]] 행에 대한 정보가 있기 떄문에 행 index로 인덱싱
print("5번 2차원 행만 인덱싱\n",arr[ [0,1] ] ,"\n") # [0,1] 행 index (열 index를 주지 않았을 때) 
print("6번 행,열 인덱싱\n",arr[ [0,1,1],[1,1,2] ] ,"\n") # (0,1)의 값과 (1,1)의 값과 (1,1)의 값을 인덱싱

# 추가적으로 정수 배열을 이용해서 할 수있는 것들
arr3 = np.array( [ 2,4,5,6,7,8,9,10,14,16,18])
int_index_array = np.array([0,0,1,4,5,6,6,6])
new_arr = arr3[int_index_array] 
print("새로운 배열 생성",new_arr)

원본
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

1번 인덱싱  2 

2번 인덱싱  2 

3번 1차원 행만 인덱싱
 [1 2] 

4번 1차원 행 2차원 인덱싱
 [[1 2 3]] 

5번 2차원 행만 인덱싱
 [[1 2 3]
 [4 5 6]] 

6번 행,열 인덱싱
 [2 5 6] 

새로운 배열 생성 [2 2 4 7 8 9 9 9]


In [30]:
# 슬라이싱 (리턴이 되는 형태를 설명 안한 것 같아서 넣었습니다. 출력에 [] 가 몇개 있는지 참고하시면 되겠습니다.)
# 배열[a:b:c , d:e:f] 일때 a,d는 시작값, b,e는 도착값, c,f는 간격
print("1번 \n",arr[ : ],"\n")   #arr[ 시작값:끝값:간격 ,  : ] 
print("2번 행 \n",arr[ 0     ,  :   ],"\n") #1차원 배열로 반환   (:없이 입력을 하게 되면 일차원 반환)
print("2번 열 \n",arr[   :   , 1 ],"\n") #1차원 배열로 반환
print("3번 \n",   arr[   : 2 ],"\n")      #2차원 배열로 반환
print("4번 \n",   arr[ 0 : 2 ,  :   ],"\n") #2차원 배열로 반환
print("5번 \n",   arr[   : 2 ,  : 1 ],"\n") #2차원 배열로 반환
print("6번 \n",   arr[   : 1 ,  : 2 ],"\n") #2차원 배열로 반환

1번 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

2번 행 
 [1 2 3] 

2번 열 
 [2 5 8] 

3번 
 [[1 2 3]
 [4 5 6]] 

4번 
 [[1 2 3]
 [4 5 6]] 

5번 
 [[1]
 [4]] 

6번 
 [[1 2]] 



In [32]:
""" 
왜 [1,0,0]이 아니고 [0,0,0] 나올까? 
답 : 10번째 줄에서 10의 값을 1로 바꾸어 주었기 때문입니다. cond로 했을때는 [True, False,False] 값이 저장이 되어있기
     때문에 arr의 정보를 바꾸어 주어도 상관이 없어서 [1,0,0]으로 출력이 되었던 것입니다~
     [1,0,0]을 보고 싶으시면 10번째 코드를 밑에서 실행 해주시면 되겠습니다.
"""
arr = np.array([10, 20, 30])
cond = arr == 10
print("전",arr)
arr[cond] = 1
print("1로변경",arr)
arr[~(cond)] = 0
print("후",arr)

전 [10 20 30]
1로변경 [ 1 20 30]
후 [1 0 0]


In [35]:
arr = np.array([10, 20, 30])
print("전",arr)
arr[~(arr == 10)] = 0
arr[(arr == 10)] = 1
print("후",arr)

전 [10 20 30]
후 [1 0 0]
